version: '3.9'
services:
  db:
    image: postgres:14
    env_file: ./server/.env
    expose:
      - '5432'
    user: postgres
    volumes:
      - db:/app/postgresql/data
      - ./server/utils:/docker-entrypoint-initdb.d

  server:
    # env_file: .env
    build: ./server/ # look for Dockerfile and build
    ports:
      - '8080:8080'
    volumes:
      - ./server/:/app # copyinh server dir
      - /app/node_modules
    environment:
      - NODE_ENV=development

  client:
    # env_file: .env
    build: ./client/ # look for Dockerfile and build
    ports:
      - '3000:3000'
    volumes:
      - ./client/:/app
      - /app/node_modules
    depends_on:
      - server
volumes:
  db: